import { describe, expect, it } from "vitest";
import {
  buildGeneratedConfig,
  renderGeneratedConfigYaml,
  renderExampleWorkflow
} from "../../src/cli/init/renderer.js";
import { validateConfig } from "../../src/config/schema.js";

describe("Init Renderer Services", () => {
  const options = {
    cwd: "/project",
    interactive: false,
    force: false,
    strict: false,
    runSmokeTest: false,
    smokeReport: "pretty" as const,
    workflowsDir: "/project/workflows",
    agentsDir: "/project/.open-dynamic-workflow/agents",
    toolsDir: "/project/.open-dynamic-workflow/tools"
  };

  describe("buildGeneratedConfig", () => {
    it("generates a valid config for mock provider", () => {
      const config = buildGeneratedConfig({
        options,
        selectedProvider: "mock"
      });

      expect(config.defaultProvider).toBe("mock");
      expect(config.providers.mock).toBeDefined();
      expect(config.providers.codex).toBeUndefined();
      
      // Should not throw
      validateConfig(config);
    });

    it("generates a valid config for external provider", () => {
      const config = buildGeneratedConfig({
        options,
        selectedProvider: "codex"
      });

      expect(config.defaultProvider).toBe("codex");
      expect(config.providers.mock).toBeDefined();
      expect(config.providers.codex).toBeDefined();
      
      // Should not throw
      validateConfig(config);
    });

    it("reflects custom directories in config", () => {
      const customOptions = {
        ...options,
        workflowsDir: "/project/flows",
        agentsDir: "/project/cfg/agents",
        toolsDir: "/project/cfg/tools"
      };

      const config = buildGeneratedConfig({
        options: customOptions,
        selectedProvider: "mock"
      });

      expect(config.sharedAgents.dir).toBeUndefined();
      expect(config.tools.dir).toBeUndefined();
      expect((config.workflow as any).discovery).toBeUndefined();

      expect(config.sharedAgents.include).toContain("cfg/agents/**/*.agent.ts");
      expect(config.sharedAgents.include).toContain("cfg/agents/**/*.agent.js");
      expect(config.sharedAgents.exclude).toContain("**/*.test.*");
      expect(config.sharedAgents.exclude).toContain("**/*.spec.*");

      expect(config.tools?.include).toContain("cfg/tools/**/*.tool.ts");
      expect(config.tools?.include).toContain("cfg/tools/**/*.tool.js");
      expect(config.tools?.exclude).toContain("**/*.test.*");
      expect(config.tools?.exclude).toContain("**/*.spec.*");

      expect(config.workflow.include).toContain("flows/**/*.workflow.ts");
      expect(config.workflow.include).toContain("flows/**/*.workflow.js");
      expect(config.workflow.exclude).toContain("**/*.test.*");
      expect(config.workflow.exclude).toContain("**/*.spec.*");
    });
  });

  describe("renderGeneratedConfigYaml", () => {
    it("renders valid YAML with comment", () => {
      const config = buildGeneratedConfig({
        options,
        selectedProvider: "mock"
      });

      const yaml = renderGeneratedConfigYaml(config);
      expect(yaml).toContain("# Generated by open-dynamic-workflow init.");
      expect(yaml).toContain("defaultProvider: mock");
    });
  });

  describe("renderExampleWorkflow", () => {
    it("renders a valid workflow template", () => {
      const workflow = renderExampleWorkflow();
      expect(workflow).toContain("export const meta =");
      expect(workflow).toContain('name: "example-workflow"');
      expect(workflow).toContain('phase("run")');
      expect(workflow).toContain("await agent({");
      expect(workflow).not.toContain("provider:");
    });
  });
});
