import { describe, expect, it } from "vitest";
import {
  buildGeneratedConfig,
  renderGeneratedConfigYaml,
  renderExampleWorkflow,
  loadGlobalsDeclaration,
  renderExampleTool
} from "../../src/cli/init/renderer.js";
import { validateConfig } from "../../src/config/schema.js";
import { parse as parseYaml } from "yaml";

describe("Init Renderer Services", () => {
  const options = {
    cwd: "/project",
    interactive: false,
    force: false,
    strict: false,
    runSmokeTest: false,
    smokeReport: "pretty" as const,
    workflowsDir: "/project/workflows",
    agentsDir: "/project/.open-dynamic-workflow/agents",
    toolsDir: "/project/.open-dynamic-workflow/tools"
  };

  describe("buildGeneratedConfig", () => {
    it("generates a valid config for mock provider", () => {
      const config = buildGeneratedConfig({
        options,
        selectedProvider: "mock"
      });

      expect(config.defaultProvider).toBe("mock");
      expect(config.outDir).toBe(".open-dynamic-workflow/runs");
      expect(config.providers.mock).toBeDefined();
      expect(config.providers.codex).toBeUndefined();
      
      // Should not throw
      validateConfig(config);
    });

    it("generates a valid config for external provider", () => {
      const config = buildGeneratedConfig({
        options,
        selectedProvider: "codex"
      });

      expect(config.defaultProvider).toBe("codex");
      expect(config.providers.mock).toBeDefined();
      expect(config.providers.codex).toBeDefined();
      
      // Should not throw
      validateConfig(config);
    });

    it("reflects custom directories in config", () => {
      const customOptions = {
        ...options,
        workflowsDir: "/project/flows",
        agentsDir: "/project/cfg/agents",
        toolsDir: "/project/cfg/tools"
      };

      const config = buildGeneratedConfig({
        options: customOptions,
        selectedProvider: "mock"
      });

      expect(config.sharedAgents.dir).toBeUndefined();
      expect(config.tools.dir).toBeUndefined();
      expect((config.workflow as any).discovery).toBeUndefined();

      expect(config.sharedAgents.include).toContain("cfg/agents/**/*.ts");
      expect(config.sharedAgents.include).toContain("cfg/agents/**/*.js");
      expect(config.sharedAgents.exclude).toBeUndefined();

      expect(config.tools?.include).toContain("cfg/tools/**/*.ts");
      expect(config.tools?.include).toContain("cfg/tools/**/*.js");
      expect(config.tools?.exclude).toBeUndefined();

      expect(config.workflow.include).toContain("flows/**/*.workflow.ts");
      expect(config.workflow.include).toContain("flows/**/*.workflow.js");
      expect(config.workflow.exclude).toBeUndefined();
    });
  });

  describe("renderGeneratedConfigYaml", () => {
    it("renders valid YAML with comment", () => {
      const config = buildGeneratedConfig({
        options,
        selectedProvider: "mock"
      });

      const yaml = renderGeneratedConfigYaml(config);
      expect(yaml).toContain("# Generated by open-dynamic-workflow init.");
      expect(yaml).toContain("defaultProvider: mock");
      expect(parseYaml(yaml).outDir).toBe(".open-dynamic-workflow/runs");
      expect(() => validateConfig(config)).not.toThrow();
    });
  });

  describe("renderExampleWorkflow", () => {
    it("renders a valid workflow template", () => {
      const workflow = renderExampleWorkflow();
      expect(workflow).toContain("export const meta =");
      expect(workflow).toContain('name: "example-workflow"');
      expect(workflow).toContain('phase("run")');
      expect(workflow).toContain("await agent({");
      expect(workflow).not.toContain("provider:");
      
      // Global context assertions
      expect(workflow).toContain('context.set("projectName", "starter-project")');
      expect(workflow).toContain('projectName: context.get("projectName")');
      expect(workflow).not.toContain("ctx.context");
      expect(workflow).not.toContain("context:");
    });
  });

  describe("loadGlobalsDeclaration", () => {
    it("loads globals declaration containing the ambient names and contracts", async () => {
      const decl = await loadGlobalsDeclaration();
      expect(decl).toContain("interface OdwToolExecutionContext");
      expect(decl).toContain("interface OdwToolDefinition");
      expect(decl).toContain("declare function defineTool");
      expect(decl).toContain("runId: string");
      expect(decl).toContain("toolCallId: string");
      expect(decl).toContain("definitionId: string");
      expect(decl).toContain("workflowInvocationId: string");
      expect(decl).toContain("artifactsDir: string");
      expect(decl).toContain("signal: AbortSignal");
      expect(decl).toContain("log(message: string, data?: unknown): void");
      expect(decl).not.toContain("@travisliu/open-dynamic-workflow");
    });
  });

  describe("renderExampleTool", () => {
    it("renders tool template referencing globals correctly", () => {
      const starterPath = "/project/.open-dynamic-workflow/tools/example.tool.ts";
      const globalsPath = "/project/.open-dynamic-workflow/globals.d.ts";
      const tool = renderExampleTool(starterPath, globalsPath);

      expect(tool).toContain('/// <reference path="../globals.d.ts" />');
      expect(tool).toContain("export default defineTool(");
      expect(tool).toContain('id: "example-tool"');
      expect(tool).not.toContain("@travisliu/open-dynamic-workflow");
    });

    it("renders correct reference path for custom tools directory", () => {
      const starterPath = "/project/custom-tools/example.tool.ts";
      const globalsPath = "/project/.open-dynamic-workflow/globals.d.ts";
      const tool = renderExampleTool(starterPath, globalsPath);

      expect(tool).toContain('/// <reference path="../.open-dynamic-workflow/globals.d.ts" />');
      expect(tool).toContain("export default defineTool(");
    });

    it("renders correct reference path for same directory", () => {
      const starterPath = "/project/.open-dynamic-workflow/example.tool.ts";
      const globalsPath = "/project/.open-dynamic-workflow/globals.d.ts";
      const tool = renderExampleTool(starterPath, globalsPath);

      expect(tool).toContain('/// <reference path="./globals.d.ts" />');
    });
  });
});
