import { readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { join, dirname, relative } from "node:path";
import { stringify } from "yaml";
import { getBuiltInProviderDefaults } from "../../config/defaults.js";
import { validateConfig } from "../../config/schema.js";
import type { OpenDynamicWorkflowConfig } from "../../config/types.js";
import type { ResolvedInitOptions, SupportedInitProvider } from "./types.js";
import {
  workflowIncludePatterns,
  sharedAgentIncludePatterns,
  toolIncludePatterns,
  toDisplayPath
} from "./defaults.js";

export function buildGeneratedConfig(input: {
  options: ResolvedInitOptions;
  selectedProvider: SupportedInitProvider;
}): OpenDynamicWorkflowConfig {
  const { options, selectedProvider } = input;
  const builtInDefaults = getBuiltInProviderDefaults();

  const providers: Record<string, any> = {
    mock: builtInDefaults.mock
  };

  if (selectedProvider !== "mock" && (builtInDefaults as any)[selectedProvider]) {
    providers[selectedProvider] = (builtInDefaults as any)[selectedProvider];
  }

  const workflowsDirDisplay = toDisplayPath(options.cwd, options.workflowsDir);
  const agentsDirDisplay = toDisplayPath(options.cwd, options.agentsDir);
  const toolsDirDisplay = toDisplayPath(options.cwd, options.toolsDir);

  const config: OpenDynamicWorkflowConfig = {
    outDir: ".open-dynamic-workflow/runs",
    defaultProvider: selectedProvider,
    concurrency: 4,
    timeoutMs: 900000,
    failFast: false,
    providers,
    security: {
      allowWorkflowImports: false,
      passEnv: [],
      redactEnv: [
        "OPENAI_API_KEY",
        "GEMINI_API_KEY",
        "GOOGLE_API_KEY",
        "*_KEY",
        "*_TOKEN",
        "*_SECRET",
        "PASSWORD"
      ]
    },
    reporting: {
      mode: "pretty",
      verbose: false
    },
    sharedAgents: {
      include: sharedAgentIncludePatterns(agentsDirDisplay),
      maxDefinitions: 100,
      allowDynamicIds: false,
      strictPromptTemplateVariables: true
    },
    tools: {
      include: toolIncludePatterns(toolsDirDisplay),
      concurrency: 4,
      maxDefinitions: 100
    },
    workflow: {
      include: workflowIncludePatterns(workflowsDirDisplay),
      maxDepth: 8,
      maxLoopRounds: 20
    }
  };

  validateConfig(config);
  return config;
}

export function renderGeneratedConfigYaml(config: OpenDynamicWorkflowConfig): string {
  const comment = "# Generated by open-dynamic-workflow init.\n";
  return comment + stringify(config, { indent: 2, sortMapEntries: true });
}

export function renderExampleWorkflow(): string {
  return `export const meta = {
  name: "example-workflow",
  description: "A starter Open Dynamic Workflow workflow created by open-dynamic-workflow init.",
  phases: ["run"]
};

phase("run");

context.set("projectName", "starter-project");

const result = await agent({
  id: "starter-task",
  prompt: "Explain what this starter Open Dynamic Workflow workflow does."
});

export default {
  result,
  projectName: context.get("projectName")
};
`;
}

const __dirname = dirname(fileURLToPath(import.meta.url));

export async function loadGlobalsDeclaration(): Promise<string> {
  const templatePath = join(__dirname, "templates", "tool-runtime-globals.d.ts");
  const content = await readFile(templatePath, "utf-8");
  return content.replace(/\r\n/g, "\n");
}

export function renderExampleTool(starterToolPath: string, globalsPath: string): string {
  let rel = relative(dirname(starterToolPath), globalsPath);
  rel = rel.split(/[\\/]/).join("/");
  if (!rel.startsWith(".") && !rel.includes("/")) {
    rel = "./" + rel;
  }
  return `/// <reference path="${rel}" />

export default defineTool({
  id: "example-tool",
  description: "A starter Open Dynamic Workflow tool that echoes input.",
  inputSchema: {
    type: "object",
    properties: {
      message: { type: "string" }
    },
    required: ["message"]
  },
  outputSchema: {
    type: "object",
    properties: {
      echo: { type: "string" }
    },
    required: ["echo"]
  },
  run(input: { message: string }, context) {
    context.log("Executing example-tool", { message: input.message });
    return {
      echo: input.message
    };
  }
});
`;
}
