import { stringify } from "yaml";
import { getBuiltInProviderDefaults } from "../../config/defaults.js";
import { validateConfig } from "../../config/schema.js";
import type { OpenDynamicWorkflowConfig } from "../../config/types.js";
import type { ResolvedInitOptions, SupportedInitProvider } from "./types.js";
import { workflowIncludePattern, toDisplayPath } from "./defaults.js";

export function buildGeneratedConfig(input: {
  options: ResolvedInitOptions;
  selectedProvider: SupportedInitProvider;
}): OpenDynamicWorkflowConfig {
  const { options, selectedProvider } = input;
  const builtInDefaults = getBuiltInProviderDefaults();

  const providers: Record<string, any> = {
    mock: builtInDefaults.mock
  };

  if (selectedProvider !== "mock" && (builtInDefaults as any)[selectedProvider]) {
    providers[selectedProvider] = (builtInDefaults as any)[selectedProvider];
  }

  const workflowsDirDisplay = toDisplayPath(options.cwd, options.workflowsDir);
  const agentsDirDisplay = toDisplayPath(options.cwd, options.agentsDir);
  const toolsDirDisplay = toDisplayPath(options.cwd, options.toolsDir);

  const config: OpenDynamicWorkflowConfig = {
    defaultProvider: selectedProvider,
    concurrency: 4,
    timeoutMs: 900000,
    failFast: false,
    providers,
    security: {
      allowWorkflowImports: false,
      passEnv: [],
      redactEnv: [
        "OPENAI_API_KEY",
        "GEMINI_API_KEY",
        "GOOGLE_API_KEY",
        "*_KEY",
        "*_TOKEN",
        "*_SECRET",
        "PASSWORD"
      ]
    },
    reporting: {
      mode: "pretty",
      verbose: false
    },
    sharedAgents: {
      dir: agentsDirDisplay,
      maxDefinitions: 100,
      allowDynamicIds: false,
      strictPromptTemplateVariables: true
    },
    tools: {
      dir: toolsDirDisplay,
      concurrency: 4,
      maxDefinitions: 100
    },
    workflow: {
      discovery: {
        include: [workflowIncludePattern(workflowsDirDisplay)]
      },
      maxDepth: 8,
      maxLoopRounds: 20
    }
  };

  validateConfig(config);
  return config;
}

export function renderGeneratedConfigYaml(config: OpenDynamicWorkflowConfig): string {
  const comment = "# Generated by open-dynamic-workflow init.\n";
  return comment + stringify(config, { indent: 2, sortMapEntries: true });
}

export function renderExampleWorkflow(): string {
  return `export const meta = {
  name: "example-workflow",
  description: "A starter Open Dynamic Workflow workflow created by open-dynamic-workflow init.",
  phases: ["run"]
};

phase("run");

const result = await agent({
  id: "starter-task",
  prompt: "Explain what this starter Open Dynamic Workflow workflow does."
});

export default {
  result
};
`;
}
